---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: pull docker image
      shell: docker pull arnabxyz/devops
    - name: running container
      shell: docker run -it -d arnabxyz/devops
